name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - run: echo `${{ secrets.MY_SECRET }} ${{ vars.MY_VARIABLE }} !`
